name: Deploy Andita

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
	  host: 109.111.53.203
          username: dendy
          port: 2222
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/andita
            git pull origin main
            php artisan migrate --force
            php artisan config:clear
